### ISSUE TITLE
DFS in Europe

### ISSUE THREAD

**Issue by TomK** [sultanxda/android_kernel_google_wahoo#5] opened 2020-06-24 17:14 UTC
[original post on XDA](https://forum.xda-developers.com/showpost.php?p=82627357&postcount=1779)

Is it possible to enable wifi Dynamic Frequency Selection (DFS) channels in Europe with a kernel patch? No Pixel phones support it, but other androids phones work just fine.

There are a number of threads relating to this issue (sorry, i don't have privileges to make them links):
https://www.kteem.net/2018/03/why-cant-google-pixel-use-5ghz-wi-fi.html - (brief summary of DFS)
https://forum.dji.com/thread-100550-1-1.html - (relating to wifi enabled drones)
https://reddit.com/r/GooglePixel/comments/61xxwo/pixel_never_connects_to_5ghz_on_google_wifi/
https://issuetracker.google.com/issues?q=pixel%20DFS%20wifi - (google issue tracker, most of which are set to WONTFIX)

As I understand it, it's awkward to go through certification to enable them, so they simply disable those channels in Europe. The usual advice is "change the channel on your router/AP", unfortunately not all wireless devices are configurable to that extent.

**Comment by kerneltoast** [comment] 2020-07-11 06:24
@TomK Install this kernel, turn on WiFi, grab a dmesg log, and then upload it: 
[Sultan-kernel-wahoo-DFSprint_20200710.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4906382/Sultan-kernel-wahoo-DFSprint_20200710.zip)

**Comment by TomK** [comment] 2020-07-11 07:07
thank you [dmesg.log](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4906420/dmesg.log)

**Comment by kerneltoast** [comment] 2020-07-11 07:26
@TomK See if DFS works with this kernel: 
[Sultan-kernel-wahoo-DFS_FCC_20200711.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4906435/Sultan-kernel-wahoo-DFS_FCC_20200711.zip)

**Comment by TomK** [comment] 2020-07-11 12:20
@kerneltoast no luck with that one I'm afraid
![Screenshot_20200711-115003](https://user-images.githubusercontent.com/299656/87223986-4851c900-c379-11ea-8d87-a210bc575a14.png)

**Comment by TomK** [comment] 2020-07-11 12:52
For clarity, this is an android auto hotspot. The creation of the WiFi network on the device seems to be orchestrated via some Bluetooth negotiation. The network then persists on the device.

**Comment by TomK** [comment] 2020-07-17 09:34
@kerneltoast let me know if there's any more logs I can provide to help track this down. Hope your house move went well!

**Comment by kerneltoast** [comment] 2020-07-17 15:12
@TomK Sorry I'm dragging my feet on this, I've just been busy since my move and could be busy for the next 2-3 weeks as well. I haven't forgotten about this though, and I'm thinking I may be able to reproduce the issue by changing my phone's regulatory domain to the UK, which would make debugging a whole lot faster.

**Comment by TomK** [comment] 2020-09-07 10:35
@kerneltoast hope all is well with you.  I know life has become busy, so is there anything I can do to help cover some ground with the DFS issue?

**Comment by kerneltoast** [comment] 2020-09-10 21:26
@TomK yeah life has been very busy for me for the past 2 months, and it's going to get even busier starting next week. Is the DFS issue a matter of no DFS channels working at all, or some DFS channels working but not others?

**Comment by TomK** [comment] 2020-09-11 08:09
@kerneltoast as i understand it, the pixel phones don't scan any frequency marked as DFS in the current regulatory domain.
It is possible to (sometimes) work around it by going to aeroplane mode, restarting, enabling wifi, then connecting to the DFS channel before the location is discovered.

**Comment by kerneltoast** [comment] 2020-12-31 08:59
I tried a bit and I couldn't get this working. I've stopped using this device, so I'm closing the issue.

**Closed as completed by kerneltoast** 2020-12-31 08:59 UTC
